name: Publish

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install uv and ruff
        run: pip install uv ruff
      - name: Install the project
        run: uv sync
      - name: Ruff check
        run: ruff check
      - name: Build the project
        run: uv run build --no-sources
      - name: Upload the project to PyPI
        run: uv run publish
